### ISSUE TITLE
文章列表的标题为h2，改为h1为佳

### ISSUE THREAD

**Issue by JeffreyZhao** [JeffreyZhao/blog-theme#4]
如何改成h1（方便写详细页），并保证语义正确？

**Comment by wintercn** [comment]
hmmmmm 这个其实是html不太完善的地方 h1-h6本身设计的就蛮粗糙的 其实也没有绝对的用法规定

**Comment by JeffreyZhao** [comment]
我的想法主要是，详细页里需要用h1来作为文章标题，而列表其实就是不断重复一篇一篇文章，所以希望用h1作为标题的元素，方便实现。你上次说，语义上可以在不同的Section（还是别的什么名字）里出现各自的h1，这具体是什么样的呢？

**Comment by wintercn** [comment]
我现在已经用了Section Section里面放h1也不算很反语义

**Comment by JeffreyZhao** [comment]
“不算很反语义”，不知道有没有更标准的做法？我想既然在搞这块了，那么就搞搞严谨……

**Comment by wintercn** [comment]
据我最新调查 果然就该这么用 section里面放h1

**Comment by wintercn** [comment]
resolve鸟 来close吧

**Comment by JeffreyZhao** [comment]
赞，下次你也可以自己close。

**Comment by wintercn** [comment]
我们要保持谁开的谁关的优良传统啊
